-- ============================================================
-- NotebookMind — Migration 11: cache generated Learn-mode challenges
-- Run AFTER migrations 1-10. Idempotent.
--
-- Learn-mode challenges (fix-the-bug / write-the-cell / MC) were regenerated by
-- the AI on every reload. This table caches the generated challenge per user +
-- notebook + cell so the app loads it instead of paying for generation again
-- (and the student sees the same task when they come back). Quizzes reuse the
-- existing quiz_sessions table; flashcards + section notes already persist.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.notebook_challenges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  notebook_key text NOT NULL,
  cell_index integer NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, notebook_key, cell_index)
);

ALTER TABLE public.notebook_challenges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users view own challenges" ON public.notebook_challenges;
CREATE POLICY "Users view own challenges" ON public.notebook_challenges
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users insert own challenges" ON public.notebook_challenges;
CREATE POLICY "Users insert own challenges" ON public.notebook_challenges
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users update own challenges" ON public.notebook_challenges;
CREATE POLICY "Users update own challenges" ON public.notebook_challenges
  FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users delete own challenges" ON public.notebook_challenges;
CREATE POLICY "Users delete own challenges" ON public.notebook_challenges
  FOR DELETE USING (auth.uid() = user_id);
